#Copyright © 2017 VMware, Inc. All Rights Reserved.
#SPDX-License-Identifier: MIT
---
sudo: required
language: python
cache: pip
services:
  - docker
install:
  - pip install molecule
  # - pip install required driver (e.g. docker, python-vagrant, shade)
  - pip install docker
script:
  - rm tests/group_vars/*/vault.yml
  - >
    sed -i.orig 's;  playbook.*;  playbook: tests/travis.yml;' molecule.yml
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
